# Generated by Django 4.1.5 on 2023-01-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('DateId', models.AutoField(primary_key=True, serialize=False)),
                ('WeekType', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=20)),
                ('Hour', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('GroupId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=20)),
                ('Level', models.CharField(max_length=20)),
                ('Semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('ProfessorId', models.AutoField(primary_key=True, serialize=False)),
                ('ProfessorName', models.CharField(max_length=100)),
                ('ProfessorDegree', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('LessonId', models.AutoField(primary_key=True, serialize=False)),
                ('LessonName', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=20)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.dates')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.groups')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.professors')),
            ],
        ),
    ]
